const sb=supabase.createClient(KFC_CONFIG.SUPABASE_URL,KFC_CONFIG.SUPABASE_KEY),$=x=>document.getElementById(x);let profile,raw=[];
const fmt=t=>t?new Date(t).toLocaleString("zh-TW",{timeZone:"Asia/Taipei"}):"尚無檢查紀錄";
async function init(){const {data:{session}}=await sb.auth.getSession();if(!session)return location.replace("./login.html");const {data:p,error}=await sb.rpc("my_admin_profile");if(error||!p?.length)return location.replace("./login.html");profile=p[0];if(profile.role==="op")$("opData").style.display="block";$("who").textContent=profile.role==="op"?"OP｜全市場":profile.center_name;const {data:cs}=await sb.rpc("admin_allowed_centers");$("center").innerHTML=(profile.role==="op"?'<option value="">全部中心</option>':"")+(cs||[]).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");if(profile.role!=="op"){$("center").value=profile.center_id;$("center").disabled=true}$("date").value=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei"}).format(new Date());load();if(profile.role==="op"){loadOldCount();loadArchiveCounts()}}
async function load(){const {data,error}=await sb.rpc("secure_admin_daily_bike_status",{p_center_id:$("center").value||null,p_date:$("date").value});if(error)return $("msg").textContent="載入失敗："+error.message;raw=data||[];let n=raw.length,c=raw.filter(x=>x.inspection_id).length,a=raw.filter(x=>x.inspection_status==="abnormal").length,m=raw.reduce((s,x)=>s+Number(x.open_maintenance_count||0),0);$("total").textContent=n;$("checked").textContent=c;$("unchecked").textContent=n-c;$("abnormal").textContent=a;$("openmaint").textContent=m;$("completion").textContent=n?`完成率 ${(c/n*100).toFixed(1)}%`:"";render()}
function render(){let a=raw,f=$("filter").value;if(f==="completed")a=a.filter(x=>x.inspection_id);if(f==="incomplete")a=a.filter(x=>!x.inspection_id);if(f==="abnormal")a=a.filter(x=>x.inspection_status==="abnormal");$("rows").innerHTML=a.map(x=>`<tr><td>${x.center_name}</td><td><b>${x.plate}</b></td><td>${x.vehicle_type||""}</td><td>${x.inspection_id?(x.inspection_status==="abnormal"?"<span class='badge abnormal'>異常</span>":"<span class='badge normal'>已完成</span>"):"<span class='badge uninspected'>未完成</span>"}</td><td>${x.inspection_id?fmt(x.inspected_at):"-"}</td><td>${fmt(x.last_inspected_at)}</td><td>${x.inspector_name||"-"}</td><td>${x.mileage??"-"}</td><td>${x.open_maintenance_count?`<span class="badge pending">${x.open_maintenance_count} 項未完成</span>`:"-"}</td></tr>`).join("")}
async function exp(){const {data,error}=await sb.rpc("secure_admin_inspection_export",{p_center_id:$("center").value||null,p_from_date:$("date").value,p_to_date:$("date").value});if(error)return alert(error.message);let d=data||[];if($("filter").value==="abnormal")d=d.filter(x=>x.status==="abnormal");if(!d.length)return alert("沒有可匯出的檢查資料");const ws=XLSX.utils.json_to_sheet(d),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"檢查明細");XLSX.writeFile(wb,`KFC機車檢查明細_${$("date").value}.xlsx`)}
$("refresh").onclick=load;$("center").onchange=load;$("date").onchange=load;$("filter").onchange=render;$("export").onclick=exp;$("logout").onclick=async e=>{e.preventDefault();await sb.auth.signOut();location.replace("./login.html")};init();
function cutoffDate(){const d=new Date();d.setMonth(d.getMonth()-3);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei"}).format(d)}
async function loadOldCount(){const {data,error}=await sb.rpc("op_old_inspection_count");$("oldCount").textContent=error?"讀取失敗":`3 個月前共有 ${data||0} 筆`}
async function exportOld(){const {data,error}=await sb.rpc("op_old_inspection_export");if(error)return alert(error.message);if(!data?.length)return alert("目前沒有 3 個月前的資料");const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"3個月前檢查明細");XLSX.writeFile(wb,`KFC歷史檢查備份_截止${cutoffDate()}.xlsx`)}
async function deleteOld(){const {data:n,error:e}=await sb.rpc("op_old_inspection_count");if(e)return alert(e.message);if(!n)return alert("目前沒有可清除的資料");if(!confirm(`即將永久刪除 3 個月前 ${n} 筆檢查明細。\\n\\n請確認已先匯出 Excel 備份。\\n\\n確定繼續？`))return;const phrase=prompt('最後確認：請輸入「清除歷史資料」');if(phrase!=="清除歷史資料")return alert("已取消");const {data,error}=await sb.rpc("op_delete_old_inspections",{p_confirm:"清除歷史資料"});if(error)return alert("刪除失敗："+error.message);alert(`已清除 ${data} 筆歷史檢查資料`);load();loadOldCount()}
document.addEventListener("DOMContentLoaded",()=>{const a=$("exportOld"),d=$("deleteOld");if(a)a.onclick=exportOld;if(d)d.onclick=deleteOld});

async function loadArchiveCounts(){
 const [{data:m,error:me},{data:d,error:de}]=await Promise.all([sb.rpc("op_old_completed_maintenance_count"),sb.rpc("op_old_completed_dashcam_count")]);
 $("oldMaintCount").textContent=me?"讀取失敗":`3 個月前已完成：${m||0} 筆`;
 $("oldDashCount").textContent=de?"讀取失敗":`3 個月前已完成：${d||0} 筆`;
}
async function exportArchive(rpc,sheet,file){const {data,error}=await sb.rpc(rpc);if(error)return alert(error.message);if(!data?.length)return alert("目前沒有符合條件的資料");const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet);XLSX.writeFile(wb,file)}
async function deleteArchive(countRpc,deleteRpc,label){
 const {data:n,error:e}=await sb.rpc(countRpc);if(e)return alert(e.message);if(!n)return alert("目前沒有可清除的資料");
 if(!confirm(`即將永久刪除 ${n} 筆「${label}」。\n\n待處理/維修中資料不會刪除。\n請確認已先匯出 Excel 備份。`))return;
 const phrase=prompt('最後確認：請輸入「清除歷史資料」');if(phrase!=="清除歷史資料")return alert("已取消");
 const {data,error}=await sb.rpc(deleteRpc,{p_confirm:"清除歷史資料"});if(error)return alert(error.message);alert(`已清除 ${data} 筆`);loadArchiveCounts()
}
document.addEventListener("DOMContentLoaded",()=>{
 $("exportOldMaint")&&($("exportOldMaint").onclick=()=>exportArchive("op_old_completed_maintenance_export","已完成維修",`KFC已完成維修備份_${cutoffDate()}.xlsx`));
 $("deleteOldMaint")&&($("deleteOldMaint").onclick=()=>deleteArchive("op_old_completed_maintenance_count","op_delete_old_completed_maintenance","3 個月前已完成機車維修"));
 $("exportOldDash")&&($("exportOldDash").onclick=()=>exportArchive("op_old_completed_dashcam_export","已完成紀錄器異常",`KFC行車紀錄器異常備份_${cutoffDate()}.xlsx`));
 $("deleteOldDash")&&($("deleteOldDash").onclick=()=>deleteArchive("op_old_completed_dashcam_count","op_delete_old_completed_dashcam","3 個月前已完成行車紀錄器異常"));
});
