const sb=supabase.createClient(KFC_CONFIG.SUPABASE_URL,KFC_CONFIG.SUPABASE_KEY),$=x=>document.getElementById(x);
let restaurant=null,timer,stream=null,confirmedCode="",scanRunning=false;
async function init(){const {data,error}=await sb.from("centers").select("id,code,name").eq("active",true);if(error)return;$("center").innerHTML='<option value="">請選擇外送中心</option>'+[...(data||[])].sort((a,b)=>({TP01:1,NT01:2,TY01:3,TC01:4,TN01:5,KH01:6}[a.code]||99)-({TP01:1,NT01:2,TY01:3,TC01:4,TN01:5,KH01:6}[b.code]||99)).map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}
function proceed(code){code=String(code||"").trim();if(!code)return alert("請先掃描 QR Code 或輸入電池編號");confirmedCode=code;$("batteryCode").value=code;$("batteryDisplay").textContent=`電池編號：${code}`;stopCamera();$("scanStep").classList.add("hidden");$("form").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
$("confirmCode").onclick=()=>proceed($("batteryCode").value);
$("changeBattery").onclick=()=>{confirmedCode="";$("form").classList.add("hidden");$("scanStep").classList.remove("hidden");$("msg").textContent="";scrollTo({top:0,behavior:"smooth"})};
$("scan").onclick=startCamera;$("stopScan").onclick=stopCamera;
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});$("video").srcObject=stream;$("cameraBox").style.display="block";await $("video").play();scanRunning=true;$("scanHelp").textContent="請將電池 QR Code 對準鏡頭";if("BarcodeDetector"in window){try{const d=new BarcodeDetector({formats:["qr_code"]});nativeLoop(d);return}catch(e){}}jsqrLoop()}catch(e){$("scanHelp").textContent="無法開啟相機，請確認瀏覽器相機權限，或改用手動輸入。"}}
async function nativeLoop(d){if(!scanRunning)return;try{const codes=await d.detect($("video"));if(codes.length)return proceed(codes[0].rawValue)}catch(e){}requestAnimationFrame(()=>nativeLoop(d))}
function jsqrLoop(){if(!scanRunning)return;const v=$("video"),c=$("scanCanvas");if(v.readyState>=2){c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext("2d",{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);const img=x.getImageData(0,0,c.width,c.height);if(window.jsQR){const code=jsQR(img.data,img.width,img.height,{inversionAttempts:"dontInvert"});if(code?.data)return proceed(code.data)}}requestAnimationFrame(jsqrLoop)}
function stopCamera(){scanRunning=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$("cameraBox").style.display="none"}
$("center").onchange=()=>{restaurant=null;$("restaurantSearch").value="";$("restaurantResults").innerHTML="";$("restaurantSelected").innerHTML=""};
$("restaurantSearch").oninput=()=>{restaurant=null;$("restaurantSelected").innerHTML="";clearTimeout(timer);timer=setTimeout(searchR,180)};
async function searchR(){const q=$("restaurantSearch").value.trim();if(!q||!$("center").value)return;const {data,error}=await sb.rpc("public_restaurant_search",{p_center_id:$("center").value,p_keyword:q});if(error)return;$("restaurantResults").innerHTML=(data||[]).map((r,i)=>`<div class="result" data-i="${i}"><b>${r.name}</b><small>${r.store_no||""}</small></div>`).join("")||'<div class="result">找不到餐廳</div>';document.querySelectorAll("[data-i]").forEach(e=>e.onclick=()=>{restaurant=data[+e.dataset.i];$("restaurantSearch").value=restaurant.name;$("restaurantResults").innerHTML="";$("restaurantSelected").className="chosen";$("restaurantSelected").textContent=`✓ 已選擇：${restaurant.name}`})}
$("form").onsubmit=async e=>{e.preventDefault();if(!confirmedCode)return alert("請先掃描電池 QR Code");if(!restaurant)return alert("請選擇放置餐廳");const {error}=await sb.rpc("report_battery_fault",{p_restaurant_id:restaurant.id,p_battery_code:confirmedCode,p_reported_by:$("reporter").value.trim(),p_issue_description:$("issue").value.trim()});if(error)return $("msg").textContent="送出失敗："+error.message;$("msg").textContent="✓ 電池故障已回報";setTimeout(()=>location.href="./index.html",900)};
addEventListener("beforeunload",stopCamera);init();