const sb=supabase.createClient(KFC_CONFIG.SUPABASE_URL,KFC_CONFIG.SUPABASE_KEY),$=x=>document.getElementById(x);let bike=null,timer;
const items=[["engine_ok","引擎發動"],["front_brake_ok","前煞系統"],["rear_brake_ok","後煞系統"],["headlight_ok","車頭大燈"],["tire_ok","輪胎"],["dashcam_ok","行車紀錄器"]];
$("checks").innerHTML=items.map(x=>`<div class="check"><span>${x[1]}</span><select id="${x[0]}"><option value="true">正常</option><option value="false">異常</option></select></div>`).join("");
async function centers(){let {data,error}=await sb.from("centers").select("id,code,name").eq("active",true).order("name");if(error){$("center").innerHTML="<option>中心載入失敗</option>";return}$("center").innerHTML='<option value="">請選擇領車中心</option>'+data.map(c=>`<option value="${c.id}">${c.name}</option>`).join("");let p=new URLSearchParams(location.search).get("center"),c=data.find(x=>x.code===p);if(c){$("center").value=c.id;$("search").disabled=false}}
$("center").onchange=()=>{bike=null;$("search").value="";$("results").innerHTML="";$("selected").innerHTML="";$("search").disabled=!$("center").value};
$("search").oninput=()=>{clearTimeout(timer);timer=setTimeout(search,250)};
async function search(){let q=$("search").value.trim().toUpperCase();if(q.length<2||!$("center").value){$("results").innerHTML="";return}let {data,error}=await sb.from("bikes").select("id,plate,vehicle_type,center_id").eq("active",true).eq("center_id",$("center").value).ilike("plate",`%${q}%`).limit(10);if(error){$("results").innerHTML='<div class="result">搜尋失敗</div>';return}$("results").innerHTML=data.length?data.map((b,i)=>`<div class="result" data-i="${i}"><strong>${b.plate}</strong><small>${b.vehicle_type==="electric"?"電動車":"油車"}</small></div>`).join(""):'<div class="result">找不到車牌</div>';document.querySelectorAll("[data-i]").forEach(e=>e.onclick=()=>choose(data[+e.dataset.i]))}
function choose(b){bike=b;$("search").value=b.plate;$("results").innerHTML="";$("selected").className="chosen";$("selected").innerHTML=`✓ 已選擇 <strong>${b.plate}</strong>・${b.vehicle_type==="electric"?"電動車":"油車"}`;$("energyTitle").textContent=b.vehicle_type==="electric"?"目前電量 %":"目前汽油存量 %"}
$("form").onsubmit=async e=>{e.preventDefault();if(!bike)return message("請先選擇車輛",0);let btn=$("submit");btn.disabled=true;btn.textContent="送出中...";let oks=Object.fromEntries(items.map(x=>[x[0],$(x[0]).value==="true"])),bad=Object.values(oks).some(v=>!v)||$("tread").value==="true";let payload={center_id:$("center").value,bike_id:bike.id,inspector_name:$("inspector").value.trim(),dashcam_number:$("dashcam").value.trim()||null,mileage:+$("mileage").value,front_tire_pressure:+$("front").value,rear_tire_pressure:+$("rear").value,tire_tread_abnormal:$("tread").value==="true",cup_holder_qty:+$("cups").value,delivery_bag_qty:+$("bags").value,fuel_battery_level:$("energy").value?+$("energy").value:null,...oks,status:bad?"abnormal":"normal",note:$("note").value.trim()||null};let {error}=await sb.from("inspections").insert(payload);if(error){message("送出失敗："+error.message,0);btn.disabled=false;btn.textContent="確認並送出";return}message(`✓ 已送出｜${bike.plate}｜${bad?"異常":"正常"}`,1);e.target.reset();bike=null;$("selected").innerHTML="";$("search").disabled=true;btn.disabled=false;btn.textContent="確認並送出";centers()};
function message(t,ok){$("msg").className="msg "+(ok?"ok":"err");$("msg").textContent=t}centers();