const sb=supabase.createClient(KFC_CONFIG.SUPABASE_URL,KFC_CONFIG.SUPABASE_KEY),$=x=>document.getElementById(x);let bike=null,restaurant=null,timer,restaurantTimer;
const items=[["engine_ok","引擎發動"],["front_brake_ok","前煞系統"],["rear_brake_ok","後煞系統"],["headlight_ok","車頭大燈"],["brake_light_ok","煞車燈"],["tire_ok","輪胎"],["other_ok","其他"]];
$("checks").innerHTML=items.map(x=>`<div class="check"><span>${x[1]}</span><select id="${x[0]}"><option value="true">正常</option><option value="false">異常</option></select></div>`).join("");
$("other_ok").onchange=()=>{$("otherIssue").classList.toggle("hidden",$("other_ok").value==="true");if($("other_ok").value==="true")$("otherIssue").value=""};
document.querySelectorAll(".fuel-option").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".fuel-option").forEach(x=>x.classList.remove("selected-option"));btn.classList.add("selected-option");$("fuelCardStatus").value=btn.dataset.value;});
async function loadCenters(){const {data,error}=await sb.from("centers").select("id,code,name").eq("active",true).order("name");if(error){$("center").innerHTML="<option>中心載入失敗</option>";return}$("center").innerHTML='<option value="">請選擇領車中心</option>'+[...data].sort((a,b)=>({TP01:1,NT01:2,TY01:3,TC01:4,TN01:5,KH01:6}[a.code]||99)-({TP01:1,NT01:2,TY01:3,TC01:4,TN01:5,KH01:6}[b.code]||99)).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");const p=new URLSearchParams(location.search).get("center"),c=data.find(x=>x.code===p);if(c){$("center").value=c.id;$("search").disabled=false}}
$("center").onchange=()=>{bike=null;restaurant=null;$("search").value="";$("results").innerHTML="";$("selected").innerHTML="";$("bikeWarning").innerHTML="";$("search").disabled=!$("center").value;$("restaurantSearch").value="";$("restaurantResults").innerHTML="";$("restaurantSelected").innerHTML="";$("restaurantSearch").disabled=!$("center").value};
$("search").oninput=()=>{clearTimeout(timer);timer=setTimeout(searchBike,250)};
$("restaurantSearch").oninput=()=>{restaurant=null;$("restaurantSelected").innerHTML="";clearTimeout(restaurantTimer);restaurantTimer=setTimeout(searchRestaurant,250)};
async function searchRestaurant(){
 const q=$("restaurantSearch").value.trim();
 if(q.length<1||!$("center").value){$("restaurantResults").innerHTML="";return}
 const {data,error}=await sb.from("restaurants").select("id,name,store_no,center_id").eq("active",true).eq("center_id",$("center").value).or(`name.ilike.%${q}%,store_no.ilike.%${q}%`).order("name").limit(10);
 if(error){$("restaurantResults").innerHTML=`<div class="result">餐廳搜尋失敗：${error.message||"權限錯誤"}</div>`;return}
 $("restaurantResults").innerHTML=data?.length?data.map((r,i)=>`<div class="result" data-r="${i}"><strong>${r.name}</strong><small>${r.store_no}</small></div>`).join(""):'<div class="result">找不到餐廳</div>';
 document.querySelectorAll("[data-r]").forEach(e=>e.onclick=()=>chooseRestaurant(data[+e.dataset.r]))
}
function chooseRestaurant(r){restaurant=r;$("restaurantSearch").value=r.name;$("restaurantResults").innerHTML="";$("restaurantSelected").className="chosen";$("restaurantSelected").innerHTML=`✓ 已選擇 <strong>${r.name}</strong>・${r.store_no}`}

async function searchBike(){const q=$("search").value.trim().toUpperCase();if(q.length<2||!$("center").value){$("results").innerHTML="";return}const {data,error}=await sb.from("bikes").select("id,plate,vehicle_type,center_id").eq("active",true).eq("center_id",$("center").value).ilike("plate",`%${q}%`).limit(10);if(error){console.error("Bike search error:",error);$("results").innerHTML=`<div class="result">搜尋失敗：${error.message||"權限錯誤"}</div>`;return}$("results").innerHTML=data.length?data.map((b,i)=>`<div class="result" data-i="${i}"><strong>${b.plate}</strong><small>${vehicleLabel(b.vehicle_type)}</small></div>`).join(""):'<div class="result">找不到車牌</div>';document.querySelectorAll("[data-i]").forEach(e=>e.onclick=()=>chooseBike(data[+e.dataset.i]))}
function vehicleLabel(v){return /電|electric/i.test(v||"")?"電動車":"油車"}
async function chooseBike(b){bike=b;$("search").value=b.plate;$("results").innerHTML="";$("selected").className="chosen";$("selected").innerHTML=`✓ 已選擇 <strong>${b.plate}</strong>・${vehicleLabel(b.vehicle_type)}`;await loadBikeWarnings()}
async function loadBikeWarnings(){if(!bike)return;const {data,error}=await sb.rpc("get_open_bike_maintenance",{p_bike_id:bike.id});if(error){$("bikeWarning").innerHTML='<div class="warning">無法讀取維修狀態</div>';return}if(!data?.length){$("bikeWarning").innerHTML="";return}$("bikeWarning").innerHTML=`<div class="warning"><h3>⚠ 此機車有尚未完成的維修項目</h3>${data.map(x=>`<div class="issue"><strong>${x.issue_description||"待維修"}</strong><br><small>${new Date(x.reported_at).toLocaleString("zh-TW")}</small></div>`).join("")}<p><small>請由後台「維修追蹤」確認完成；完成後此提示即不再出現。</small></p></div>`}
$("checkDashcam").onclick=loadDashcamWarnings;
async function loadDashcamWarnings(){const no=$("dashcam").value.trim();if(!no)return message("請先輸入行車紀錄器號碼",0);const {data,error}=await sb.rpc("get_open_dashcam_issues",{p_dashcam_number:no});if(error){$("dashcamWarning").innerHTML='<div class="warning">無法讀取紀錄器狀態</div>';return}if(!data?.length){$("dashcamWarning").innerHTML='<div class="chosen">✓ 目前沒有未完成的行車紀錄器異常</div>';return}$("dashcamWarning").innerHTML=`<div class="warning"><h3>⚠ 此行車紀錄器有未完成異常</h3>${data.map(x=>`<div class="issue"><strong>${x.issue_description}</strong></div>`).join("")}</div>`}
$("dashcamAbnormal").onchange=()=>$("dashcamIssue").classList.toggle("hidden",!$("dashcamAbnormal").checked);
$("form").onsubmit=async e=>{e.preventDefault();if(!bike)return message("請先搜尋並選擇機車",0);if(!restaurant)return message("請搜尋並選擇「領取餐廳」",0);if(!$("fuelCardStatus").value)return message("請選擇加油卡狀態",0);if($("other_ok").value==="false"&&!$("otherIssue").value.trim())return message("請輸入「其他」異常內容",0);if($("dashcamAbnormal").checked&&(!$("dashcam").value.trim()||!$("dashcamIssue").value.trim()))return message("請輸入行車紀錄器號碼及異常內容",0);
const btn=$("submit");btn.disabled=true;btn.textContent="送出中...";
const oks=Object.fromEntries(items.map(x=>[x[0],$(x[0]).value==="true"])),pressureOk=$("tire_pressure_ok").value==="true";
const bad=Object.values(oks).some(v=>!v)||!pressureOk||$("tread").value==="true";
const payload={center_id:$("center").value,bike_id:bike.id,inspector_name:$("inspector").value.trim(),dashcam_number:$("dashcam").value.trim()||null,mileage:+$("mileage").value,front_tire_pressure:null,rear_tire_pressure:null,tire_pressure_ok:pressureOk,tire_tread_abnormal:$("tread").value==="true",fuel_card_status:$("fuelCardStatus").value,fuel_battery_level:null,restaurant_id:restaurant.id,...oks,other_issue:$("otherIssue").value.trim()||null,dashcam_ok:null,status:bad?"abnormal":"normal",note:$("note").value.trim()||null};
const {error}=await sb.from("inspections").insert(payload);if(error){message("送出失敗："+error.message,0);btn.disabled=false;btn.textContent="確認並送出";return}
if($("dashcamAbnormal").checked)await sb.rpc("report_dashcam_issue_with_restaurant",{p_center_id:$("center").value,p_restaurant_id:restaurant.id,p_dashcam_number:$("dashcam").value.trim(),p_issue_description:$("dashcamIssue").value.trim(),p_reported_by:$("inspector").value.trim()});
message(`✓ 已送出｜${bike.plate}｜${bad?"機車有異常，已建立待維修":"機車正常"}`,1);e.target.reset();document.querySelectorAll(".fuel-option").forEach(x=>x.classList.remove("selected-option"));bike=null;restaurant=null;$("selected").innerHTML="";$("bikeWarning").innerHTML="";$("dashcamWarning").innerHTML="";$("otherIssue").classList.add("hidden");$("dashcamIssue").classList.add("hidden");$("search").disabled=true;$("restaurantSearch").value="";$("restaurantResults").innerHTML="";$("restaurantSelected").innerHTML="";$("restaurantSearch").disabled=true;btn.disabled=false;btn.textContent="確認並送出";loadCenters()};
function message(t,ok){$("msg").className="msg "+(ok?"ok":"err");$("msg").textContent=t}loadCenters();